n1 = int(input("수를 입력하세요 :"))
n2 = int(input("수를 입력하세요 :"))
n3 = int(input("수를 입력하세요 :"))
n4 = int(input("수를 입력하세요 :"))
n5 = int(input("수를 입력하세요 :"))
n6 = int(input("수를 입력하세요 :"))
n7 = int(input("수를 입력하세요 :"))
n8 = int(input("수를 입력하세요 :"))
n9 = int(input("수를 입력하세요 :"))
n10 = int(input("수를 입력하세요 :"))
print("최대값 :",n7,"최소값 :",n2)